config/routes.rb
Rails.application.routes.draw do
  resources :plants
  root 'pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'get_geocode_results', to: 'plants#geo_results'
  get 'get_spec_results', to: 'plants#spec_results'
  get 'generate_graph', to: 'pages#plant_graph'
  get 'species_fill', to: 'plants#species_fill'
  post 'login', to: 'sessions#create'
  get 'leaderboard', to: 'pages#leaderboard'
  delete 'logout', to: 'sessions#destroy'
  get '/.well-known/acme-challenge/M07Vfx66cOZKwYaSmjzUBXtZSvanu-QCJZFhMD9NZnc', to: 'pages#certbot_key'
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
    include Gravtastic
        gravtastic
    include ActionView::Helpers::DateHelper
    require 'twilio-ruby'
    attr_accessor :remember_token

    has_many :plants, dependent: :destroy

    # Case insensitivity for email
    before_save { self.email = email.downcase }
    # Makes sure user name is present
    validates :name, presence: true
    # Makes sure email is present and valid
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
    # Ensures phone number fits correct format (+110000000000) and is unique
    validates :phone, length: { is: 10 }, format: { with: /04\d{8}/, message: "number must be a correctly formatted Victorian number (10 digits, 04...)" }, uniqueness: true
    # Makes sure password is present
    has_secure_password
    validates :password, presence: true
    
    # Twilio Account ID
    @@twilio_account_id = 'AC1f9a60a66869c95de7e80492d52f3dd3'
    # Twilio API id
    @@twilio_api_sid = "SKa9acd53d62bbe66526c78b7bd6105c13"
    # Twilio API secret
    @@twilio_api_secret = "soqB2yV9co4lyJoRS0UW7HQiCom8lbEP"
    # Twilio Phone number,The web app will use this number for sending messages to Users
    @@twilio_phone = "+61488856462"
    
    # Creates digest for keeping a user logged in
    # Based on Michael Hartl's Rails Tutorial, Chapter 8
    # https://3rd-edition.railstutorial.org/book/log_in_log_out#code-user_model_remember
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    # Returns true if given remember token matches decrypted remember digest
    # Based on Michael Hartl's Rails Tutorial, Chapter 8
    # https://3rd-edition.railstutorial.org/book/log_in_log_out#code-authenticated_p
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    # Removes remember digest from user
    # Based on Michael Hartl's Rails Tutorial, Chapter 8
    # https://3rd-edition.railstutorial.org/book/log_in_log_out#code-user_model_forget
    def forget
        update_attribute(:remember_digest, nil)
    end

    # Takes a string and returns its digest
    # Based on Michael Hartl's Rails Tutorial, Chapter 8
    # https://3rd-edition.railstutorial.org/book/log_in_log_out#code-digest_method
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    # Generates a new token for user
    def User.new_token
        SecureRandom.urlsafe_base64
    end

    # Generates a user name with styled <span> tags if user is admin
    def get_styled_name
        if (admin)
            name_span = "<span class=\"admin\">" << name << "</span>"
        else
            name_span = name
        end
        name_span.html_safe
    end

    # Generates a user name with styled <span> tags if user is admin
    def get_styled_class
        if (admin)
            "admin"
        end
    end

    # Returns last time active in words (e.g. 1 minute ago) or "Never" if there is no last_active
    def last_active_in_words_or_never
        last_active
        if !last_active.nil?
            time_ago_in_words(last_active) << " ago"
        else "Never"
        end
    end

    def notify(body)
        begin
            # Makes a client with above values
            if @client.nil?
                @client = Twilio::REST::Client.new @@twilio_api_sid, @@twilio_api_secret, @@twilio_account_id
            end
            to = "+61" + phone # user.phone = "+04,d{8}"
            @client.messages.create({
            from: @@twilio_phone,
            to: to,
            body:body
            })
        
        rescue Twilio::REST::TwilioError  => exception
            puts exception.message
        end 
    end

    def  User.daily_notify
        @users = User.all
        @users.each do |user|
            if user && user.recieve_texts && !user.plants.empty?
                message="Plant Summary for: "+ user.name
                user.plants.each do |plant|
                    if plant
                        message+="\n"
                        message+="Plant: "+plant.name
                        message+="\n"
                        if plant.watered?
                            message+="Has been watered."
                        else 
                            message+="Needs to be watered\!"
                        end
                        message+="\n"
                        if plant.sunlight?
                            message+="Has been put in sunlight."
                        else
                            message+="Needs to be put in sunlight\!"
                        end
                        message+="\n"
                        if plant.relocated?
                            message+="Has been relocated."
                        end
                    end
                end
                user.notify(message)
                message=""
            end
        end
    end

    # This method will compare forecasted weather of next day from plants location
    # Against their outside plants paramaters, if exceeded (e.g: temp > plants max_temp) 
    # Notifies user to relocate their plant to indoors.
    def User.danger_check
        @users = User.all
        @users.each do |user|
            if user&&user.recieve_texts?&&!user.plants.empty?
                user.plants.each do |plant|
                    if plant.outside
                        forecast = plant.get_forecast
                        
                        plant_info = plant.get_plant
                        toSend = ""
                        if forecast && plant_info
                            # Max Temp
                            tempToUse = nil
                            # Use entered max_temp if avaliable
                            if plant.max_temp
                                tempToUse = plant.max_temp
                            else
                                tempToUse = plant_info["data"]["growth"]["maximum_temperature"]["deg_c"].to_d
                            end
                            if forecast["daily"][1]["temp"]["max"] && tempToUse
                                if forecast["daily"][1]["temp"]["max"].to_i>=tempToUse
                                    toSend+="The temperature tommorow might be a bit hot for your plant "+plant.name+". Consider keeping it inside if possible."
                                end
                            end
                            # Min Temp
                            tempToUse = nil
                            # Use entered min_temp if avaliable
                            if plant.min_temp
                                tempToUse = plant.min_temp
                            else
                                tempToUse = plant_info["data"]["growth"]["minimum_temperature"]["deg_c"].to_d
                            end
                            if forecast["daily"][1]["temp"]["min"] && tempToUse
                                if forecast["daily"][1]["temp"]["min"].to_i<=tempToUse
                                    toSend+="The temperature tommorow might be a bit cold for your plant "+plant.name+". Consider keeping it inside if possible."
                                end
                            end
                            # Wind speed, 14 m/s is considered alarming speeds
                            if forecast["daily"][1]["wind_speed"]
                                if forecast["daily"][1]["wind_speed"].to_i>=14
                                    toSend+="The wind tommorow will be quite windy for your plant "+plant.name+". Consider keeping it inside if possible."
                                end
                            end
                            user.notify(toSend)
                        end
                    end
                end
            end
        end
    end

    def User.reset_daily
        @users = User.all
        @users.each do |user|
            if user&&DateTime.current-7.days <= user.last_active
                user.plants.each do |plant|
                    if plant
                        plant.watered = false
                        plant.sunlight = false
                        # Opting to not reset relocated, as one might keep a plant out/in for multiple days
                        # plant.relocated = false
                        plant.save
                    end
                end
            end
        end
    end

    def User.calculate_score
        users = User.all
        users.each do |user|
            plants = user.plants
            points = 0
            plants.each do |plant|
                records = plant.plant_records
                record_count = 0
                records.order(created_at: :desc).each do |record|
                    if record.water_recorded
                        record_count+=1
                        points+=100*record_count
                    else
                        record_count=0
                    end
                end
            end
            user.points = points
            user.save(validate: false)
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:new, :create]
  

  # GET /users
  # GET /users.json
  # Redirect to home page with a danger message if user is not logged in or is not an administrator
  def index
    unless logged_in? && current_user.admin
      redirect_to root_path
      flash[:danger] = 'Only administrators can view the list of users'
    end
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  # Redirect to home page with a danger message if user is not logged in, not the specified user or is not an administrator
  def show
    if !(logged_in?)
      redirect_to root_path
      flash[:danger] = 'You must be logged in to view a user.'
    elsif !(current_user.admin || current_user == @user)
      redirect_to root_path
      if (@user.admin)
        flash[:danger] = 'You do not have the power to see an admin.'
      else
        flash[:danger] = 'You do not have the power to see another user.'
      end
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  # Redirect to home page with a danger message if user is not logged in, not the specified user or is not an administrator
  def edit
    if !(logged_in?)
      redirect_to root_path
      flash[:danger] = 'You must be logged in to edit a user.'
    elsif !(current_user.admin || current_user == @user)
      redirect_to root_path
      if (@user.admin)
        flash[:danger] = 'You do not have the power to edit an admin.'
      else
        flash[:danger] = 'You do not have the power to edit another user.'
      end
    end
  end

  # POST /users
  # POST /users.json
  # Code based on Michael Hartl's Rails Tutorial, Chapter 7
  # https://3rd-edition.railstutorial.org/book/sign_up#code-signup_flash
  def create
    @user = User.new(user_params)
    @user.points = 0
    @user.last_active = DateTime.now
    # If administrator boolean is not set, set it to false
    # This will happen when a user signs up and there is already an admin, since the admin checkbox will not show
    if (@user.admin.nil?)
      @user.admin = false
    end
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path
                      flash[:success] = 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        @user.notify("Welcome to the plant monitoring system "+@user.name+"!\n Get started by adding a plant.")
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  # Code based on Michael Hartl's Rails Tutorial, Chapter 9
  # https://3rd-edition.railstutorial.org/book/updating_and_deleting_users#code-user_update_action
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  # Code based on Michael Hartl's Rails Tutorial, Chapter 9
  # https://3rd-edition.railstutorial.org/book/updating_and_deleting_users#code-destroy_action
  # Redirect to home page with a danger message if user is not logged in, not the specified user or is not an administrator
  # Or else destroy user
  def destroy
    if !(logged_in?)
      redirect_to root_path
      flash[:danger] = 'You must be logged in to destroy a user.'
    elsif !(current_user.admin || current_user == @user)
      redirect_to root_path
      if (@user.admin)
        flash[:danger] = 'You do not have the power to destroy an admin.'
      else
        flash[:danger] = 'You do not have the power to destroy another user.'
      end
    else
      # Log user out if they are logged in and to be destroyed
      if (@user == current_user)
        log_out_no_redirect
      end
      # Destroy all users plants 
      @user.plants.each do |plant|
        plant.destroy
      end
      # Do the deed
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :phone, :password, :admin, :recieve_texts, :competitive)
    end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_badges.html.erb
<div class="user-page-badges points-badges">
    <%#Only show points badges if one avaliable%>
    <%if user.points && user.points >= 46500%>
    <%# Badges for plant maintnance %>
    <strong>Badges for plant maintnance:</strong><br>

    <%# One plant for a month %>
    <% if user.points >= 46500 %>
        <%= image_tag("badge-graphic.png", alt: "Bronze badge graphic", class: "badge-medium tip-prompt") %>
        <div class = "tooltip">
        <strong>BRONZE BADGE</strong><br>
        This bronze badge is rewarded to users with 465,000 points or more.
        </div>
    <% end %>

    <%# One plant for half a year %>
    <% if user.points >= 1665300 %>
        <%= image_tag("badge-graphic2.png", alt: "Silver badge graphic", class: "badge-medium tip-prompt") %>
        <div class = "tooltip">
        <strong>SILVER BADGE</strong><br>
        This silver badge is rewarded to users with 1,665,300 points or more.
        </div>
    <% end %>

    <%# One plant for a year %>
    <% if user.points >= 6643000 %>
        <%= image_tag("badge-graphic3.png", alt: "Gold badge graphic", class: "badge-medium tip-prompt") %>
        <div class = "tooltip">
        <strong>GOLD BADGE</strong><br>
        This golden badge is rewarded to users with 6,643,000 points or more.
        </div>
    <% end %>

    <% end %>
</div>
<div class="user-page-badges attendance-badges">
    <%if DateTime.current-1.month >= user.created_at%>
        <%# Badges for site attendence %>
        <strong>Badges for site attendence:</strong><br>
        <%# One month of attendence %>
        <%if DateTime.current-1.month >= user.created_at %>
        <%= image_tag("badge-graphic.png", alt: "Bronze badge graphic", class: "badge-medium tip-prompt") %>
        <div class = "tooltip">
            <strong>BRONZE BADGE</strong><br>
            This bronze badge is rewarded to users who have been with us for a month.
        </div>
        <%end%>
        <%# six months of attendence %>
        <%if DateTime.current-6.month >= user.created_at %>
        <%= image_tag("badge-graphic2.png", alt: "Silver badge graphic", class: "badge-medium tip-prompt") %>
        <div class = "tooltip">
            <strong>SILVER BADGE</strong><br>
            This silver badge is rewarded to users who have been with us for six months.
        </div>
        <%end%>
        <%# 1 year of attendence %>
        <%if DateTime.current-1.year >= user.created_at %>
        <%= image_tag("badge-graphic3.png", alt: "Gold badge graphic", class: "badge-medium tip-prompt") %>
        <div class = "tooltip">
            <strong>GOLD BADGE</strong><br>
            This golden badge is rewarded to users who have been with us for a year.
        </div>
        <%end%>

    <%end%>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field custom-control custom-switch">
    <%= form.check_box :recieve_texts, class:"custom-control-input", id:"customSwitch1" %>
    <%= form.label "Recieve text notifications?", class:"custom-control-label", for:"customSwitch1" %>
    
  </div>

  <div class="field custom-control custom-switch">
    <%= form.check_box :competitive, class:"custom-control-input", id:"customSwitch2" %>
    <%= form.label "Compete in leaderboard?", class: "custom-control-label", for:"customSwitch2" %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <% if User.where(admin: true).length == 0 %>
    <div class="field">
      <%= form.label :admin %>
      <%= form.check_box :admin %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% content_for :title, "Editing #{@user.name}" %>
<h1>Editing <%= @user.get_styled_name %></h1>

<%= render 'form', user: @user %>
<%= link_to 'Show', @user %>  
<%= link_to 'Back', root_path %>

app/views/users/index.html.erb
<%= content_for :title, "Users" %>
<h1>Users</h1>
<p><%= link_to 'New User', signup_path %></p>
<div class="table-holder">
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>Last Active</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% User.order(last_active: :desc).each do |user| %>
        <tr>
          <td><%= link_to user.name, user, {class: user.get_styled_class } %></td>
          <td><%= user.email %></td>
          <td><%= user.phone if user.phone %>
          <td><%= user.last_active_in_words_or_never %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<div class="user-login">

    <%= content_for :title, "New User" %>
    <h1>New User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'Back', root_path %>
    <%= link_to 'Sign In',login_path %>

</div>

app/views/users/show.html.erb
<% content_for :title, @user.name %>

<div class="wrapper">
  <div class="split-container">
    <div class="right-container">
      

      <h1><%= @user.get_styled_name %></h1>
      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>

      <p>
        <strong>Active:</strong>
        <%=time_ago_in_words(@user.created_at)%>
      </p>

      <p>
        <strong>Phone:</strong>
        <%= @user.phone if @user.phone%>
      </p>
      <div class= "mobile-show field">
        <%=form_for(@user, id: "opt-edit", remote: true)  do |form|%>
          <div class= "custom-control custom-switch">
            
              <%= form.check_box :recieve_texts, class: "custom-control-input", id: "customSwitch1"%>
              <label class="custom-control-label inline" for="customSwitch1">Recieve Notifications</label>
              <span class="tip-prompt" tabindex="0">?</span>
              <div class = "tooltip">
                Quick edit to opt in and out of text notifications<br>
              </div><br>

              <%= form.check_box :competitive, class: "custom-control-input", id: "customSwitch2"%>
              <label class="custom-control-label inline" for="customSwitch2">Compete in Leaderboard</label>
              <span class="tip-prompt" tabindex="0">?</span>
              <div class = "tooltip">
                Quick edit to opt in and out of appearing in the leaderboard<br>
              </div><br>
            
          </div>
        <%end%>
      </div>
      <p>
        <strong>Points:</strong>
        <%= @user.points if @user.points%>
      </p>
      
      <%= render partial: "badges", locals: { user: @user } %>
      <% if @user == @current_user||@current_user.admin%>
        <%puts("is a user!")%>
        <%= link_to "Log out", logout_path(@current_user), method: :delete if @user==@current_user%>
        <%= link_to 'Edit', edit_user_path(@user) %> 
      <% end %>
    </div>

    <div class="left-container hide_in_mobile">
      <%= link_to 'Back', root_path %>
      <% @user.plants.order(:created_at).each do |current_plant| %>
        <div class="list-item">
          <br>
          <%= link_to  current_plant.name , current_plant %>
          <br>
        </div>
      <% end %>
    </div>
  </div>
</div>