config/routes.rb
Rails.application.routes.draw do
  resources :plants
  root 'pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'get_geocode_results', to: 'plants#geo_results'
  get 'get_spec_results', to: 'plants#spec_results'
  get 'generate_graph', to: 'pages#plant_graph'
  get 'species_fill', to: 'plants#species_fill'
  post 'login', to: 'sessions#create'
  get 'leaderboard', to: 'pages#leaderboard'
  delete 'logout', to: 'sessions#destroy'
  get '/.well-known/acme-challenge/M07Vfx66cOZKwYaSmjzUBXtZSvanu-QCJZFhMD9NZnc', to: 'pages#certbot_key'
  resources :users
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  has_many :plant_records, dependent: :destroy
  has_one_attached :plant_pic
  validates :name, presence: true
  # VALID_COORD_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i # (-?\d+(\.\d+)?),\s*(-?\d+(\.\d+)?)
  # validates :location, presence: true, format: {with: VALID_EMAIL_REGEX}
  
  #Weather API secret 
  @@weatherKey = '9b732f988a82cb5ec7499a0d0e6416ff'
  # Treffle ID Authentication token
  @@treffle_token = "1EuNspuzlsLWfDRrSfNIMpAUqcWNGvb3M0IQ__GxGTs"

  def get_weather
    lon=location.split(', ')[1]
    if lon 
      lon=lon.tr(']','')
    end
    lat=location.split(', ')[0]
    if lat
      lat=lat.tr('[','')
    end
    if lat && lon then
      # Don't know why, but this only functions when on one line
      ActiveSupport::JSON.decode(open("http://api.openweathermap.org/data/2.5/weather?lat="+lat+"&lon="+lon+"&APPID="+@@weatherKey+"&units=metric").read)
    end
  end

  def get_forecast
    splitLoc = location.split(',')
    lon=location.split(', ')[1]
    if lon then lon=lon.tr(']','') end
    lat=location.split(', ')[0]
    if lat then lat=lat.tr('[','') end
    # Returns the next 7 days forecast inclusive of current day
    # format is JSON in daily serperators
    # example: http://api.openweathermap.org/data/2.5/onecall?
    if lat && lon then ActiveSupport::JSON.decode(open("http://api.openweathermap.org/data/2.5/onecall?lat="+lat+"&lon="+lon+"&APPID="+@@weatherKey+"&units=metric&exclude=current,minutely,hourly,alerts").read)
    end
  end
  

  def Plant.record_values
    plants = Plant.all
    plants.each do |plant|
      # Build a plant record for this plant if there is a water level, and add if has been watered
      record = PlantRecord.new()
      if plant.daily_water and plant.watered
        record.water_recorded = plant.daily_water
      else
        record.water_recorded = nil
      end
      
      # Record average tempatrure for day
      weatherJson = plant.get_weather()
      if weatherJson["main"]
        averageWeather = (weatherJson["main"]["temp_max"]+weatherJson["main"]["temp_min"]) / 2
        record.temp_recorded = averageWeather
      end
      if record
        plant.plant_records << record
        record.save
      end
    end
  end

  # Removes all plant records over 1 year old
  def Plant.remove_old_records
    plants = Plant.all
    plants.each do |plant|
      records = plant.plant_records
      records.order(created_at: :asc).each do |record|
        if record.created_at<1.year.ago
          PlantRecord.delete(record.id)
        else
          # Small optimisation due to ordering
          break
        end
      end
    end
  end

  def get_plant    
    results = HTTParty.get(
      'https://trefle.io/api/v1/species/'+ treffleID.to_s,
    query: {
      "token": @@treffle_token
    })
    results.parsed_response
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  
  include SessionsHelper
  before_action :set_plant, only: [:show, :edit, :update, :destroy]
  require 'geocoder'
  require 'httparty'
 
  # Treffle ID Authentication token
  @@treffle_token = "1EuNspuzlsLWfDRrSfNIMpAUqcWNGvb3M0IQ__GxGTs"

  # GET /plants
  # GET /plants.json
  def index
    if current_user.admin
      @plants = Plant.all
    else
      @plants = current_user.plants
    end
  end

  # GET /plants/1
  # GET /plants/1.json
  def show
    if @plant.treffleID
      # Retirve plant details
      # plantResults = HTTParty.get(
      #   'https://trefle.io/api/v1/species/'+@plant.treffleID.to_s+"?token="+@@treffle_token
      # )
      @plants_decoded = @plant.get_plant
      if @plants_decoded && @plants_decoded["data"]
        if @plants_decoded["data"]["growth"] 
          #FURTHER SIMPLIFIY FOR CODE RESUE : @plants_decoded["data"]["growth"]  = growthResponse
          @plantDescription = @plants_decoded["data"]["growth"]["description"] 
          @plantMaxTemp = @plants_decoded["data"]["growth"]["maximum_temperature"]["deg_c"]
          @plantMinTemp = @plants_decoded["data"]["growth"]["minimum_temperature"]["deg_c"]
        end
        @plantImage = @plants_decoded["data"]["image_url"]
      end
    end
	end

  # GET /plants/new
  # Redirect to home page with a danger message if user is not logged in
  def new
    unless logged_in?
      redirect_to root_path
      flash[:danger] = 'You must be logged in to add a plant.'
    else
      @plant = Plant.new
    end
  end

  # GET /plants/1/edit
  # Redirect to home page with a danger message if user is not logged in
  def edit
    unless logged_in?
      redirect_to root_path
      flash[:danger] = 'You must be logged in to edit a plant.'
    end
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)
    # Assume first result is accurate given in form location auto-fill
    @plant.location = Geocoder.search(@plant.locationName).first.coordinates
    # Handle TreffleID assigment
    results = HTTParty.get(
      'https://trefle.io/api/v1/species/search',
      query: {
        "q": @plant.species,
        "token": @@treffle_token
      }
    )
    @species_decoded = results.parsed_response
    if @species_decoded["data"][0]
      @plant.treffleID = @species_decoded["data"][0]["id"].to_i
    end
    @plant.watered = false
    @plant.sunlight = false
    @plant.relocated = false
    @plant.user = current_user
    respond_to do |format|
      if @plant.save
        message = 'Plant was successfully updated.'
        if !@plant.daily_water
          message+= "\n Auto-fill attempt failed, please fill unfilled fields."
        end
        format.html { redirect_to root_path, notice: message}
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        # Handle location geocoding
        if plant_params[:locationName]
          searchResults = Geocoder.search(@plant.locationName)
          if searchResults.first
            @plant.location = searchResults.first.coordinates
          end
        end

        # Handle TreffleID assigment
        if plant_params[:species]
          results = HTTParty.get(
            'https://trefle.io/api/v1/species/search',
            query: {
              "q": @plant.species,
              "token": @@treffle_token
            }
          )
          species_decoded = results.parsed_response 
          if species_decoded["data"][0]
            # Assume the first result is most accurate, due to name lookup in form
            @plant.treffleID = species_decoded["data"][0]["id"].to_i
          end
        end

        if @plant.save
          message = 'Plant was successfully updated.'
          if !@plant.daily_water
            message+= "\n Auto-fill attempt failed, please fill unfilled fields."
          end
          format.html { redirect_to root_path, notice: message}
          format.json { render :show, status: :ok, location: @plant }
        else
          format.html { render :edit }
          format.json { render json: @plant.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  # Redirect to home page with a danger message if user is not logged in, or else destroy plant
  def destroy
    unless logged_in?
      redirect_to root_path
      flash[:danger] = 'You must be logged in to destroy a plant.'
    else
      @plant.destroy
      respond_to do |format|
        format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def geo_results 
    results = Geocoder.search(params['string'])
    toSend = ""
    4.times do |i|
      if results[i] != nil
        if results[i].city!=nil && results[i].county!=nil
          toSend+= results[i].city+", "+results[i].country+"|"
        elsif results[i].country!=nil
          toSend+= results[i].country+"|"
        elsif results[i].city
          toSend+= results[i].city+"|"
        end
      else 
        toSend+="|"
      end
     
    end
    render json: toSend, status: :ok
  end

  def spec_results 
    #https://trefle.io/api/v1/species/search?q=coconut&token=YOUR_TREFLE_TOKEN
    #results = 'https://trefle.io/api/v1/species/search?q='+params['toSearch']+'&token='+treffle_token
    results = HTTParty.get(
      'https://trefle.io/api/v1/species/search',
      query: {
        "q": params['toSearch'],
        "token": @@treffle_token
      }
    )
    species_decoded = results.parsed_response  
    toSend=""
    
    if species_decoded["data"] != nil
      4.times do |i|
        if species_decoded["data"][i]
          if(species_decoded["data"][i]["common_name"]!=nil)
            toSend+=species_decoded["data"][i]["common_name"]
          elsif (species_decoded["data"][i]["scientific_name"]!=nil)
            toSend+=species_decoded["data"][i]["scientific_name"]
          end
          toSend+=','
          if species_decoded["data"][i]["image_url"]
            toSend+=species_decoded["data"][i]["image_url"]
          end
          toSend+=','
          toSend+=species_decoded["data"][i]["id"].to_s
          toSend+='|'
        end
        # end the if data
      end 
      # End THE 4 loop
    end
    # end the if species
    render json: toSend, status: :ok
  end
  
  # Method to parse data into javascript files for plant form auto-fill
  # Will lookup @plant for daily water and light required fields given those fields are nil
  # Does not garuntee fields will be filled
  def species_fill
    results = HTTParty.get(
      'https://trefle.io/api/v1/species/'+ params["id"],
    query: {
      "token": @@treffle_token
    })
    @plant_decoded = results.parsed_response
    toSend=""
    if @plant_decoded["data"]["growth"]
      if @plant_decoded["data"]["growth"]["minimum_precipitation"]["mm"] && @plant_decoded["data"]["growth"]["maximum_precipitation"]["mm"]
        # Daily average = (min+max / 2) / 365
        daily_water = (@plant_decoded["data"]["growth"]["minimum_precipitation"]["mm"] + @plant_decoded["data"]["growth"]["maximum_precipitation"]["mm"] / 2) / 365
          # Round to the nearest 50ml
          daily_water= ((daily_water.to_d/50).ceil) *50
          toSend+=(daily_water).to_s
      end
      toSend+="|"
      if @plant_decoded["data"]["growth"]["light"]
        #light is in 1/1000 notation
        light = @plant_decoded["data"]["growth"]["light"]
        toSend+=(light*2000).to_s
      end
      toSend+="|"
      if @plant_decoded["data"]["growth"]["minimum_temperature"]["deg_c"]
        toSend+= @plant_decoded["data"]["growth"]["minimum_temperature"]["deg_c"].to_s
      end
      toSend+=","
      if @plant_decoded["data"]["growth"]["maximum_temperature"]["deg_c"]
        tosend += @plant_decoded["data"]["growth"]["maximum_temperature"]["deg_c"].to_s
      end
    end
    render json: toSend, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plant_params
      params.require(:plant).permit(:name, :location, :locationName, :species, :watered, :sunlight, :relocated, :daily_water, :outside, :plant_pic, :max_temp, :min_temp)
    end
  end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/_form.html.erb
<%= form_with(model: plant, class: "plant-form")do |form| %>
<div class="split-container">
  <div class="left-container">
    <% if plant.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>
        <ul>
          <% plant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <%# Calls Method in Assests/JS with #loc-field %>
    <div class="field location_field">
      <%= form.label "Search Location", class: "inline"%>
      <span class="tip-prompt" tabindex="0">?</span>
      <div class = "tooltip">
        This field will automatically suggest city names and country to select from. <br>
        Once picked, city info will be automatically filled in.<br>
        It is important to select a known location from suggestions for weather purposes.<br>
      </div><br>
      <%= form.text_field :locationName, class: "location_field", oninput: "search_locations()", autocomplete: 'off' %>
      <div class="field location_field">
      </div>
    </div>

    <div class="field species_field">
      <%= form.label :species , class: "inline" %> 
      <span class="tip-prompt" tabindex="0">?</span>
      <div class = "tooltip">
      This field will automatically suggest names of plants to select from. <br>
      Once picked, plant info will be automatically filled in to the following fields, if possible.<br>
      </div><br>
      <%= form.text_field :species, class: "species_field", oninput: "search_species()", autocomplete: 'off' %>
      <div class="field species_field">
      </div>
    </div>

    <div class = "field species_water">
      <%= form.label "Daily water (mm)", class: "inline" %>
      <span class="tip-prompt" tabindex="0">?</span>
      <div class = "tooltip">
      Represents the water needed daily for this plant to survive. <br>
      If not automatically filled, please fill.<br>
      </div><br>
      <%= form.number_field :daily_water, in: 0..12000, step: 50, id: "plant_daily_water"%>
    </div>
  
  </div>
<%
=begin%>
  End of left-contaitner div
<%
=end%>
  <div class="right-container">

  <div class = "field species_light">

    <%= form.label "Outside plant?", class: "inline" %>
    <span class="tip-prompt" tabindex="0">?</span>
    <div class = "tooltip">
      This will determine whether the plant is meant to be kept outside.<br>
      Will update upon selecting a species.<br>
      If unchecked, system interprets as an inside plant (default/unknown value)
    </div><br>
    <%=form.check_box :outside, id: "outsideSet" %>
  </div>

  <div class = "field species_temps inline"><span class="tip-prompt" tabindex="0">?</span>
    <div class = "tooltip">
      While not required to register a plant, it is used for forcasting weather.<br>
      Can be manually filled if not automatically filled when accepting a suggestion.<br>
      If unfilled, the system will attempt to lookup these values when forcasting, results not garunteed.
    </div><br>
    <%# Tese temp ranges are based on the hottest and coldest places on earth. Good luck finding a plant to exceed them.%>
    
    <%= form.label raw("Minimum temperature (°C)") %>
    <%= form.number_field :min_temp, in: -41..70, step: 0.5, id: "plant_minimum_temp"%>
    <%= form.label raw("Maximum temperature (°C)")%>
    <%= form.number_field :max_temp, in: -41..70, step: 0.5, id: "plant_maximum_temp"%>
  </div>

  <div class = "plant picture">
  <%= form.label :plant_pic, class: "inline" %><span class="tip-prompt" tabindex="0">?</span>
  <div class = "tooltip">
      If you would like to use a picture of your own plant, you can choose one from your device using the setting below.<br>
      The plant may have an existing image associated with its species, which it will fall back on if you do not provide your own picture.
  </div><br>  
  <%= form.file_field :plant_pic %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <%= link_to 'Back', plants_path, class: "hide_in_mobile" %>
    <%= link_to 'Back', root_path, class: "hide_in_desktop" %>
  </div>
  
</div>
<%
=begin%>
  End of right-container div
<%
=end%>
</div>
<%
=begin%>
  End of split-container div
<%
=end%>
<% end %>

app/views/plants/edit.html.erb
<% content_for :title, "Editing #{@plant.name}" %>
<h1>Editing <%= @plant.name %></h1>
<%= render 'form', plant: @plant %>

app/views/plants/index.html.erb
<%= content_for :title, "Plants" %>
<h1>Plants</h1>
<p><%= link_to 'New Plant', new_plant_path %></p>
<% if @plants%>
<div class="table-holder">  
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Owner</th>
        <th>Watered Today?</th>
        <th>Moved today?</th>
        <th>Relocated Today?</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @plants.each do |plant| %>
        <tr>
          <td><%= link_to plant.name, plant %></td>
          <td><%= link_to plant.user.name, plant.user, {class: plant.user.get_styled_class } %></td>
          <td><%= plant.watered %></td>
          <td><%= plant.sunlight %></td>
          <td><%= plant.relocated %></td>
          <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
          <td><%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%end%>    <%# Plants Must Exist %>

app/views/plants/new.html.erb
<% content_for :title, "New Plant" %>
<h1>New Plant</h1>
<%= render 'form', plant: @plant %>

app/views/plants/show.html.erb
<% content_for :title, @plant.name %>
<div class="split-container">
    <div class="left-container">
		<h1><%= @plant.name %></h1>
		<h3>Location: <%= @plant.locationName %></h3>
		<h4>Co-Ords: <%= @plant.location %></h4>
		<h3>Species: <%= @plant.species %></h3>
		<h3>Daily water (mm): <%= @plant.daily_water%></h3>
		<h3>Outside Plant?: <%= @plant.outside%></h3>
		<h3>Owned By: <%= @plant.user.name %></h3>
		<% if @plant.max_temp %>
			<h3>Ideal plant temperature is below: <%=@plant.max_temp%></h3>
		<%elsif @plantMaxTemp%>
			<h3>Ideal plant temperature is below: <%= @plantMinTemp %></h3>
		<%else%>
			<h3>Unknown ideal max temperature!</h3>
		<%end%>

		<% if @plant.min_temp %>
			<h3>Ideal plant temperature is above: <%= @plant.min_temp %></h3>
		<% elsif @plantMinTemp %>
			<h3>Ideal plant temperature is above: <%= @plantMinTemp %></h3>
		<%else%>
			<h3>Unknown ideal min temperature!</h3>
		<% end %>
		<%= link_to 'Edit', edit_plant_path(@plant) %> 
		<%= link_to 'Back', root_path %>

	</div>
	<div class="right-container">
		<% if @plantDescription %>
			<h3>Description: <%=@plantDescription%></h3> 
		<%end%>
		<% if @plant.watered == false %>
			<h3>Plant needs to be watered today!<h3>
		<% else %>
			<h3>Plant is happy and watered!</h3>
		<% end %>

		<% if @plant.sunlight == false %>
			<h3>Plant needs some sun today!<h3>
		<% else %>
			<h3>Plant is happy and has recived sunlight!</h3>
		<% end %>

		<% if @plant.relocated == false %>
			<h3>Plant has not been relocated.<h3>
		<% else %>
			<h3>Plant has been relocated!</h3>
		<% end %>

		<% if @plant.plant_pic.attached? %>
			<%= image_tag @plant.plant_pic, size: "400" %>
		<% elsif @plantImage %>
			<%= image_tag @plantImage, size: "400" %>
		<% else %>
			<h3>No Image!</h3>
		<%end%>
	</div>
</div>