config/routes.rb
Rails.application.routes.draw do
  resources :plants
  root 'pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'get_geocode_results', to: 'plants#geo_results'
  get 'get_spec_results', to: 'plants#spec_results'
  get 'generate_graph', to: 'pages#plant_graph'
  get 'species_fill', to: 'plants#species_fill'
  post 'login', to: 'sessions#create'
  get 'leaderboard', to: 'pages#leaderboard'
  delete 'logout', to: 'sessions#destroy'
  get '/.well-known/acme-challenge/M07Vfx66cOZKwYaSmjzUBXtZSvanu-QCJZFhMD9NZnc', to: 'pages#certbot_key'
  resources :users
end

app/views/layouts/_header.html.erb
<header> 
    <div class="wrapper head-wrapper">
        <div class="title-link">
            <%= image_tag("big-logo.png", width: "150px", class: "hide_in_mobile") %>
            <button class="hide_in_desktop menu_button" onclick="toggle_pull_right()">Menu</button>
            <%= link_to 'New Plant', new_plant_path, class: "hide_in_desktop mobile_new_plant"%>
        </div>
        <div class="header-center">
            <h1>
                <%= link_to "Plant Monitor", root_path %>
            </h1>
            <%= link_to "Leaderboard", leaderboard_path, class: "hide_in_mobile" %>
        </div>

        <%#Start of pull-right menu used for mobile-site%>
        <nav id="menu" class="menu-away hide_in_desktop">
            <button class="hide_in_desktop menu_button" onclick="toggle_pull_right()">Menu</button>
            
            <% if current_user %>
                <p>
                    <%=link_to current_user do %>
                        <%= image_tag current_user.gravatar_url , :class => "gravatar" %>
                    <% end %>
                </p>
                <p><%= current_user.name %>: <%= current_user.points %></p>
                <p><%= current_user.phone%></p>
                <hr>
                <%=form_for(current_user, id: "opt-edit", remote: true)  do |form|%>
                    <div class= "custom-control custom-switch">
                        <%= form.check_box :recieve_texts, class: "custom-control-input", id: "customSwitch1"%>
                        <label class="custom-control-label inline" for="customSwitch1">Recieve Notifications</label><br>
                        <%= form.check_box :competitive, class: "custom-control-input", id: "customSwitch2"%>
                        <label class="custom-control-label inline" for="customSwitch2">Compete in Leaderboard</label>
                    </div>
                <%end%>
                <hr>
                <%= render partial: "users/badges", locals: {user: current_user} %>
                <hr>
                <% if current_user.competitive %>
                    <h2>RANKINGS</h2>
                    <p class="ranks">
                        <% rank = 1; %>
                        <% User.order(points: :desc).each do |user| %>
                            <%if user.competitive%>
                                <%=rank%>: <%= user.get_styled_name %> (<%= user.points %>)<br>
                                <%rank+=1%>
                            <%end%>
                        <% end %>
                    </p>
                <% end %>
                <hr>
                <%= link_to "Log out", logout_path, method: :delete %>
            <% end %>
        </nav>
        
        <%# OPEN RIGHT DIV %>
        <div class="user-info hide_in_mobile">
            <div class="name-and-date">
            <% if current_user%>
                <%= if current_user.admin then link_to "Users", users_path end %> 
                <div class="date-box" title="Today is the <%= Date.today.strftime("#{Date.today.day.ordinalize} of %B, %Y") %>.">
                    <div class="day"><%= Date.today.strftime("%d") %></div>
                    <div class="month"><%= Date.today.strftime("%b").upcase %></div>
                </div>
                <div class="name-and-title">
                    <%=link_to current_user do %>
                        <%= image_tag current_user.gravatar_url , :class => "gravatar" %>
                    <% end %>
                    
                    </div>
                </div>
            <% end %> 
        </div> 
        <%# END RIGHT DIV %>
    </div>
</header>

app/views/layouts/application.html.erb
<% # Updates current user's last active date if logged in (methods in sessions controller) %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densityDpi=device-dpi" />
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg" >
  <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message.html_safe, class: "alert alert-#{message_type}")%>
    <% end %>
    <%= yield %>
  </body>
</html>